#define SDL_MAIN_HANDLED 1

#include "../inc/SDL2/SDL.h"
#include "../inc/SDL2/SDL_image.h"
#include "../inc/SDL2/SDL_main.h"

#define WINDOW_TITLE "Hello World!"
#define WINDOW_WIDTH 640
#define WINDOW_HEIGHT 480
#define WINDOW_FULLSCREEN 0
#define SCREEN_WIDTH 160
#define SCREEN_HEIGHT 96

static SDL_Window* window;
static SDL_Renderer* renderer;
static SDL_Texture* screenTexture;
static int running = 1;

/* Start() is called once at the start of the program */
int Start() {
    SDL_Init(SDL_INIT_EVERYTHING);
    IMG_Init(IMG_INIT_PNG);

    // Set up window
    window = SDL_CreateWindow(WINDOW_TITLE,
        SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
        WINDOW_WIDTH, WINDOW_HEIGHT, WINDOW_FULLSCREEN ? SDL_WINDOW_FULLSCREEN_DESKTOP : 0);
    
    if (!window) {
        SDL_Log("Failed to create window: %s", SDL_GetError());
        return 1;
    }

    SDL_SetWindowPosition(window, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
    SDL_RaiseWindow(window);


    // Set up renderer
    renderer = SDL_CreateRenderer(window, -1,
        SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED | SDL_RENDERER_TARGETTEXTURE);
    
    if (!renderer) {
        SDL_Log("Failed to create renderer: %s", SDL_GetError());
        return 1;
    }

    SDL_RenderSetLogicalSize(renderer, SCREEN_WIDTH, SCREEN_HEIGHT);
    return 0;
}

/* Update() is called every frame of the program */
int Update() {
    if(Prepare_Screen_Texture()) return 1;
    if(Render_Texture()) return 1;
    return 0;
}

/* Quit() is called once at the end of the program */
int Quit() {
    SDL_DestroyTexture(screenTexture);
    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);
    SDL_Quit();
    return 0;
}


/* Handle_Event() is called every time an event is detected (keyboard, mouse, etc.) */
int Handle_Event(SDL_Event *event) {
    switch (event->type){
        case SDL_QUIT: case SDL_KEYDOWN:  running = 0;  break;
            
        default: break;
    }
    return 0;
}

/* Prepares the screen texture */
int Prepare_Screen_Texture() {
    screenTexture = IMG_LoadTexture(renderer, "Assets/Images/image.png");
    
    if (!screenTexture) {
        SDL_Log("Failed to load image: %s", SDL_GetError());
        return 1;
    }
    return 0;
}

/* Render the current texture */
int Render_Texture() {
    SDL_FRect dstrect = { 0, 0, 160, 96 };
    SDL_RenderCopyF(renderer, screenTexture, NULL, &dstrect);
    SDL_RenderDrawRectF(renderer, &dstrect);
    SDL_RenderPresent(renderer);
    return 0;
}

/* The main function kinda generated by Windows. Similar to main()*/
int WinMain(int argc, char* argv[]) {
    if (Start()) return 1;

    SDL_Event event;
    while (running) {
        while (SDL_PollEvent(&event)) {
            if(Handle_Event(&event)) return 1;
        }
        if(Update()) return 1;
    }

    Quit();
    return 0;
}