#define SDL_MAIN_HANDLED 1

#include <app.h>
#include <SDL_main.h>
#include <input.h>

/* The main function kinda generated by Windows. Similar to main()*/
int WinMain(int argc, char* argv[]) {
    if (App_Start()) return 1;

    SDL_Event event;
    while (app.running) {
        if(App_PreUpdate()) return 1;
        while (SDL_PollEvent(&event)) {
            if(App_Event_Handler(&event)) return 1;
        }
        if(App_PostUpdate()) return 1;
    }

    App_Quit();
    return 0;
}